@startuml
state "Connection Enabled" as Connection_Enabled  {
    state "Adapter Disabled" as Adapter_Disabled  {
    }
    state "Adapter Enabled" as Adapter_Enabled  {
        state "Discover Services" as Discover_Services  {
            state "Discovering Services" as Discovering_Services  {
Discovering_Services : Enter: DiscoverServices
            }
            state "Reading Firmware" as Reading_Firmware  {
Reading_Firmware : Enter: ReadFirmware
            }
            state "Showtime" as Showtime  {
Showtime : Enter: OnEnter
            }
            state "Get Inkey" as Get_Inkey  {
Get_Inkey : Enter: RequestInkey
            }
            state "Get V2 Outkey" as Get_V2_Outkey  {
Get_V2_Outkey : Enter: GetV2Outkey
            }
            state "Get V3 Outkey" as Get_V3_Outkey  {
Get_V3_Outkey : Enter: GetV3Outkey
            }
            state "Sending Outkey" as Sending_Outkey  {
Sending_Outkey : Enter: SendOutkey
            }
            state "TODO Gatt connect failed" as TODO_Gatt_connect_failed  {
            }
            state "TODO Not Onewheel" as TODO_Not_Onewheel  {
            }
            state "Connection lost" as Connection_lost  {
            }
            state "Connecting" as Connecting  {
Connecting : Enter: TryToConnect
            }
        }
        state "Recovery" as Recovery  {
Recovery : Enter: Wait
        }
        state "TBC" as TBC  {
        }
        state "Scanning" as Scanning  {
Scanning : Enter: StartScan\nExit: StopScan
        }
    }
    state "Init" as Init  {
    }
Connection_Enabled : Enter: ListenForBluetoothToggle\nExit: StopListeningForBluetoothToggle
}
state "Connection Disabled" as Connection_Disabled  {
}
Adapter_Disabled --> Adapter_Enabled : Adapter_Enabled
Discovering_Services --> TODO_Not_Onewheel : ToDo_Not_Onewheel
Discovering_Services --> Reading_Firmware : Read_Firmware
Reading_Firmware --> Showtime : Gen_1_Firmware
Reading_Firmware --> Get_Inkey : Gemini_Firmware
Showtime --> Showtime : Received_Data
Showtime --> Connection_lost : Timeout
Get_Inkey --> Get_Inkey : Serial_Read
Get_Inkey --> Get_V2_Outkey : Inkey_Found_(V2)
Get_Inkey --> Get_V3_Outkey : Inkey_Found_(V3)
Get_V2_Outkey --> Sending_Outkey : Got_Outkey
Get_V3_Outkey --> Sending_Outkey : Got_Outkey
Sending_Outkey --> Showtime : Outkey_Written
Connecting --> Discovering_Services : Gatt_Connected
Connecting --> TODO_Gatt_connect_failed : Todo_Gatt_Connect_Fail
Discover_Services --> TBC : TBC
Recovery --> Scanning : Timeout
Scanning --> Discover_Services : Device_found
Adapter_Enabled --> Adapter_Disabled : Adapter_Disabled
Init --> Adapter_Enabled : Adapter_Enabled
Init --> Adapter_Disabled : Adapter_Disabled
Connection_Enabled --> Connection_Disabled : Disable_connection
Connection_Disabled --> Connection_Enabled : Enable_connection
 
@enduml